name: Daily Scheduled Job

# This workflow is triggered every 24 hours
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)รง

jobs:
  daily_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-x6gi.onrender.com/health
          max-attempts: 3
          retry-delay: 30s
